### ISSUE TITLE
ConfigIniParser Error: The specify option not found

### ISSUE THREAD

**Issue by enuggetry** [shangerxin/config-ini#8]
I'm getting an error on the line: 
```
var ConfigIniParser = require("config-ini-parser").ConfigIniParser;
```
```
ConfigIniParser Error: The specify option not found
    at /home/ericiam/jbconnect-test/node_modules/config-ini-parser/config-ini.js:21:39
    at Object.<anonymous> (/home/ericiam/jbconnect-test/node_modules/config-ini-parser/config-ini.js:423:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/theuser/jbconnect-test/workflows/primer3.end.js:12:17
```
node v10.x

**Comment by enuggetry** [comment]
mistake on my part.

**Comment by shangerxin** [comment]
Thank you for the feedback.
